name: 'Mirror a repository using SSH'
description: 'Action for mirroring a repository in another location (Bitbucket, GitHub, GitLab, …) using SSH.'
branding:
  icon: 'copy'
  color: 'orange'
inputs:
  source-repo:
    description: 'SSH (or HTTPS) URL of the source repo.'
    required: true
    default: ''
  destination-repo:
    description: 'SSH URL of the destination repo.'
    required: true
    default: ''
  branches:
    description: 'Optional `:` separated list of branches to mirror.'
    required: false
    default: ''
  force-push-branches:
    description: 'Force push selected branches.'
    required: false
    default: 'false'
  dry-run:
    description: 'Execute a dry run.'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-repo }}
    - ${{ inputs.destination-repo }}
    - ${{ inputs.branches }}
    - ${{ inputs.force-push-branches }}
    - ${{ inputs.dry-run }}
